### ISSUE TITLE
PrometheusMetrics::with_default_registry() panics if called more than once

### ISSUE THREAD

**Issue by henrikhorluck** [sd2k/rocket_prometheus#14] opened 2021-07-10 11:42 UTC
This is especially a problem when writing `rocket`-tests, see this minimal working example: https://github.com/henrikhorluck/prom-test

Note that the example uses https://github.com/sd2k/rocket_prometheus/pull/4, but I believe the issue is still present in `0.8.0`

**Comment by sd2k** [comment] 2021-07-20 20:44
Thanks for the report and reproducible test. This is happening because each `PrometheusMetrics` currently registers the same Rocket related metrics with the provided registry on each instantiation, and adding the same metric to a registry twice is an error.

I think this can be easily fixed by just adding a separate registry for the Rocket related metrics, which _should_ be fine -- I don't think users will care if the registry returned by `PrometheusMetrics::registry()` doesn't contain the Rocket metrics -- but I might need to deprecate that method in favour of two new, more explicit ones. I'll write a test and fix in a PR shortly.

**Closed as completed** 2021-07-21 08:35 UTC

**Comment by sd2k** [comment] 2021-07-21 08:41
@henrikhorluck That's released in version 0.8.1 and merged into the `async` branch, so you should be good to go now 👍
